version: "3.4"
services:
  db:
    image: ${DC_POSTGRES_IMAGE}
    environment:
      POSTGRES_USER: lavaserver
      POSTGRES_PASSWORD: lavaserverdbpass
    volumes:
    - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  lava-scheduler:
    image: ${DC_SERVER_IMAGE}
    volumes:
    - device-types:/etc/lava-server/dispatcher-config/device-types:ro
    - devices:/etc/lava-server/dispatcher-config/devices:ro
    - health-checks:/etc/lava-server/dispatcher-config/health-checks:ro
    - ./overlays/etc/lava-server/settings.d/01-database.yaml:/etc/lava-server/settings.d/01-database.yaml:ro
    - ./overlays/etc/lava-server/settings.d/01-events.yaml:/etc/lava-server/settings.d/01-events.yaml:ro
    - ./overlays/etc/lava-server/lava-scheduler:/etc/lava-server/lava-scheduler:ro
    depends_on:
    - db
    environment:
      SERVICES: "lava-scheduler"
    restart: unless-stopped

  lava-publisher:
    image: ${DC_SERVER_IMAGE}
    volumes:
    - ./overlays/etc/lava-server/settings.d/01-database.yaml:/etc/lava-server/settings.d/01-database.yaml:ro
    - ./overlays/etc/lava-server/settings.d/01-events.yaml:/etc/lava-server/settings.d/01-events.yaml:ro
    - ./overlays/etc/lava-server/settings.d/02-publisher.yaml:/etc/lava-server/settings.d/02-publisher.yaml:ro
    environment:
      SERVICES: "lava-publisher"
    ports:
    - 5500:5500
    - 8001:8001
    restart: unless-stopped

  lava-server:
    image: ${DC_SERVER_IMAGE}
    volumes:
    - device-types:/etc/lava-server/dispatcher-config/device-types
    - devices:/etc/lava-server/dispatcher-config/devices
    - health-checks:/etc/lava-server/dispatcher-config/health-checks
    - joboutput:/var/lib/lava-server/default/media/job-output
    - ./overlays/etc/lava-server/settings.d/01-database.yaml:/etc/lava-server/settings.d/01-database.yaml:ro
    - ./overlays/etc/lava-server/settings.d/01-events.yaml:/etc/lava-server/settings.d/01-events.yaml:ro
    - ./overlays/etc/lava-server/settings.d/01-unsecure.yaml:/etc/lava-server/settings.d/01-unsecure.yaml:ro
    - ./overlays/etc/lava-server/settings.d/02-autoregister.yaml:/etc/lava-server/settings.d/02-autoregister.yaml:ro
    depends_on:
    - db
    - lava-publisher
    - apache2
    environment:
      SERVICES: "gunicorn"
      BIND: "--bind lava-server:8000"
      LAVA_ADMIN_USERNAME: "${DC_LAVA_ADMIN_USERNAME}"
      LAVA_ADMIN_PASSWORD: "${DC_LAVA_ADMIN_PASSWORD}"
    restart: unless-stopped

  lava-coordinator:
    image: ${DC_SERVER_IMAGE}
    environment:
      SERVICES: "lava-coordinator"
    ports:
    - 3079:3079
    restart: unless-stopped

  apache2:
    image: ${DC_SERVER_IMAGE}
    volumes:
    - ./overlays/etc/apache2/sites-available/lava-server.conf:/etc/apache2/sites-available/lava-server.conf:ro
    environment:
      SERVICES: "apache2"
    ports:
    - 80:80
    restart: unless-stopped


volumes:
  db-data:
    name: lava-server-pgdata
  device-types:
    name: lava-server-device-types
  devices:
    name: lava-server-devices
  health-checks:
    name: lava-server-health-checks
  joboutput:
    name: lava-server-joboutput
